parameters:
    ikimea_page.menu_builder.class: Ikimea\PageBundle\Menu\Builder

services:
    ikimea_page.menu_builder:
      class: %ikimea_page.menu_builder.class%
      arguments: ["@knp_menu.factory"]

    ikimea_page.breadcrumb:
      class: Knp\Menu\MenuItem # the service definition requires setting the class
      factory_service: ikimea_page.menu_builder
      factory_method: breadcrumb
      arguments: ["@request"]
      scope: request # needed as we have the request as a dependency here
      tags:
        - { name: knp_menu.menu, alias: breadcrumb }
      