<?php

namespace Ikimea\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends EntityRepository
{
    public function getAllComponentsByZone($parent){
        return $this->createQueryBuilder('c')
        ->where('c.zone = :parent')
        ->setParameter('parent',$parent)
        ->getQuery()
        ->execute();
    }
}