<?php

/*
* This file is part of the Ikimea Pages package.
*
* (c) Ikimea <http://www.ikimea.com/>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Ikimea\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponentRepository extends EntityRepository
{
    public function getAllComponentsByArea($parent){
        return $this->createQueryBuilder('c')
        ->where('c.zone = :parent')
        ->setParameter('parent',$parent)
        ->getQuery()
        ->execute();
    }
}