<?php

/*
* This file is part of the Ikimea Pages package.
*
* (c) Ikimea <http://www.ikimea.com/>
*
* For the full copyright and license information, please view the LICENSE
* file that was distributed with this source code.
*/

namespace Ikimea\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComponentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    /*
     *  get page by slug
     */
    public function getPageBySlug($slug)
    {
       return $this->findOneBy(array('slug' => $slug));
    }

    /*
     *  get page by route
     */
    public function getPageByRoute($route)
    {
        return $this->findOneBy(array('route' => $route));
    }

    public function getArea($slug, $name)
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.areas', 'z')
            ->leftJoin('z.components', 'c')
            ->where('p.slug = :slug')
            ->Andwhere('z.name = :parent')
            ->setParameter('parent',$name)
            ->setParameter('slug',$slug)
            ->getQuery()
            ->getSingleResult();
    }
}